# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8f382adcc4b5a5b8099f64eabf88456a34549574a42cc5814afd782d3b5a903bd57f9b18e69f59b8b3ca3c8115f36a6796ea6e35b96644738a5fd488b19c6098
  paypal_account: blue76817-facilitator@gmail.com
  paypal_host: https://www.sandbox.paypal.com
  app_host: http://749ab35a.ngrok.io

test:
  secret_key_base: 4c811e0444f4ac03f1c191a811a7b3ddc14ab846606235f3dfe1ef3bd1913e0a6a8e884acf2239f63f81443bc0b13cb41ee805e5d8def2b86e63e748b26b044e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  paypal_account: blue76817-facilitator@gmail.com
  paypal_host: https://www.sandbox.paypal.com
  app_host: http://749ab35a.ngrok.io
